java_v: openjdk-17-jdk
shellvar: /bin/bash
httpsurl: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.44/bin/apache-tomcat-10.1.44.tar.gz 
directory: /opt/tomcat10
untarvar: /tmp/apache-tomcat-10.1.44.tar.gz
