---
- name: tomcat installation on ansible
  become: yes
  hosts: all
  tasks: 
   - name: install java upto date
     ansible.builtin.apt:
      name: "{{ java_v }}"
      state: present
   - name: create user tomcat
     ansible.builtin.user:
      name: tomcat
      create_home: yes
      home: /opt/tomcat
      shell: "{{ shellvar }}"
   - name: install tomcat
     ansible.builtin.get_url:
      url: "{{ httpsurl }}"
      dest: /tmp
   - name: directory to tomcat10
     ansible.builtin.file:
      path: "{{ directory }}"
      group: tomcat
      owner: tomcat
      state: directory
      mode: 0750
   - name: untar tomcat application
     ansible.builtin.unarchive:
      src: "{{ untarvar }}"
      dest: "{{ directory }}"
      remote_src: yes
      extra_opts: [--strip-components=1]
   - name: change ownership of a directory
     ansible.builtin.file:
      path: "{{ directory }}"
      recurse: yes
      state: directory
      owner: tomcat
      group: tomcat
   - name: copy service file of tomcat10
     ansible.builtin.copy:
      src: tomcat.service
      dest: /etc/systemd/system/tomcat.service
      remote_src: no
   - name: reload,restart daemon
     ansible.builtin.systemd_service:
      name: tomcat.service
      daemon_reload: yes
      state: restarted






      